# Generated by Django 5.2.4 on 2025-07-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/category/')),
            ],
        ),
        migrations.CreateModel(
            name='tblcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/city/')),
            ],
        ),
        migrations.CreateModel(
            name='tblseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('exp', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('resume', models.ImageField(null=True, upload_to='static/resume/')),
                ('salary', models.IntegerField(null=True)),
                ('esalary', models.IntegerField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/profile/')),
                ('regdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/team/')),
                ('post', models.CharField(max_length=30, null=True)),
                ('experience', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tblgallery',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/gallery/'),
        ),
        migrations.CreateModel(
            name='tblcompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('owner', models.CharField(max_length=200, null=True)),
                ('logo', models.ImageField(null=True, upload_to='static/logo/')),
                ('type', models.CharField(max_length=200, null=True)),
                ('detail', models.TextField(null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('startdate', models.DateField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('isimp', models.BooleanField(null=True)),
                ('ispaid', models.BooleanField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblcity')),
            ],
        ),
        migrations.CreateModel(
            name='tbljob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('jobtype', models.CharField(max_length=100, null=True)),
                ('minsalary', models.IntegerField(null=True)),
                ('maxsalary', models.IntegerField(null=True)),
                ('prefgender', models.CharField(max_length=100, null=True)),
                ('exp', models.CharField(max_length=200, null=True)),
                ('skills', models.CharField(max_length=300, null=True)),
                ('vacany', models.IntegerField(null=True)),
                ('lastdate', models.DateField(null=True)),
                ('startdate', models.DateField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblcategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblcity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblcompany')),
            ],
        ),
        migrations.CreateModel(
            name='tblapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverletter', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbljob')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblseeker')),
            ],
        ),
    ]
