# Generated by Django 5.2.4 on 2025-07-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tblcategory_tblcity_tblseeker_tblteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblseeker',
            name='id',
        ),
        migrations.AlterField(
            model_name='tblseeker',
            name='email',
            field=models.EmailField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblseeker',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile/'),
        ),
    ]
