# Generated by Django 5.2.4 on 2025-08-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_tblseeker_id_alter_tblseeker_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblapply',
            name='coverletter',
        ),
        migrations.AddField(
            model_name='tblapply',
            name='cvselected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblapply',
            name='hired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblapply',
            name='interview',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblapply',
            name='rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
